companies_storage added
Biotech-h/backend pull request #10
Opened 2022-06-07 19:07 UTC by KhramovKhramov

2022-06-07 19:16 UTC, vppuzakov requested changes
👍 все верно, теперь надо его использовать в наших views в рамках этого же ПР

2022-06-08 08:17 UTC, vppuzakov requested changes
Пофиксить вызов метода объекта класса `CompaniesStorage`

2022-06-08 17:42 UTC, KhramovKhramov commented
Еще добавил ручку на добавление компании
Через Insomnia все работает

2022-06-08 19:03 UTC, vppuzakov approved these changes
👍

2022-06-08 19:16 UTC, merged